Repository razrabs-media/editorial, pull requests merged in 2022-08, with the labels that each got.

#1 added the 'about us' article
  about-us/about-us.md
  about-us/preview.jpg
Labels: Редакция

#3 updated image in 'about-us'
  about-us/preview.jpg
Labels: Редакция

#4 updated 'who we are' article
  who-we-are/who-we-are.md
Labels: Редакция, Мнения

#5 Stay together
  stay-together/preview.jpg
  stay-together/stay-together.md
Labels: Мнения, Колонка Фила

#6 added 'tech' article
  tech-post/tech.md
Labels: Мнения, Колонка Фила

#22 jun-way: add article
  jun-way/jun-way.md
  jun-way/preview.jpg
Labels: Мнения, История, Колонка Наташи

#24 Добавлена статья Jun Way
  jun-way/jun-way.md
  jun-way/preview.jpg
Labels: Мнения, История, Колонка Наташи

#26 jun-way: добавлена статья и превью
  jun-way/jun-way.md
  jun-way/preview.jpg
Labels: Мнения, История, Колонка Наташи

#28 nat-jun-way: добавлена статья и превью
  nat-jun-way/nat-jun-way.md
  nat-jun-way/preview.jpg
Labels: Мнения, История, Колонка Наташи

#29 nat-jun-way: добавлено описание автора
  nat-jun-way/nat-jun-way.md
Labels: Мнения, История, Колонка Наташи

#30 nat-jun-way: из описания убраны ссылки
  nat-jun-way/nat-jun-way.md
Labels: Мнения, История, Колонка Наташи

#31 nat-jun-way: добавлены ссылки в саму статью
  nat-jun-way/nat-jun-way.md
Labels: Мнения, История, Колонка Наташи

#36 Add repo link
  about-us/about-us.md
Labels: Редакция

#42 iz-razrabotchikov-igr-v-razrabotchiki-servisa-balancy: adds article
  balancy/adminka_new_1.png
  balancy/adminka_old.png
  balancy/apanasik-balancy.md
  balancy/balancy-preview.png
  balancy/balancy_conditions.png
  balancy/balancy_docs.png
  balancy/balancy_nodes.png
  balancy/balancy_templates.png
  balancy/cyprus_home.jpg
  balancy/hero-masters.jpg
  balancy/unnynet.png
  balancy/unnynet_old.png
  balancy/unnyworld-prototype.jpg
Labels: Код, История, Заметки безработного, Релокейт

#40 typo(nat-jun-way): исправляет опечатку
  nat-jun-way/nat-jun-way.md
Labels: Мнения, История, Колонка Наташи

#48 updated preview
  corporate/corporate-preview.jpg
Labels: Мнения

#49 updated preview
  corporate/corporate.md
  corporate/preview.jpg
Labels: Мнения

#50 updated preview
  balancy/apanasik-balancy.md
  balancy/balancy-preview.png
  balancy/preview.jpg
Labels: Код, История, Заметки безработного, Релокейт

#51 fixed images
  balancy/adminka_new_11.png
  balancy/adminka_old1.png
  balancy/apanasik-balancy.md
  balancy/balancy_conditions1.png
  balancy/balancy_docs1.png
  balancy/balancy_nodes1.png
  balancy/balancy_templates1.png
  balancy/cyprus_home1.jpg
  balancy/hero-masters1.jpg
  balancy/unnynet1.png
  balancy/unnynet_old1.png
  balancy/unnyworld-prototype1.jpg
Labels: История, Заметки безработного, Релокейт

#54 Clay Global and fuagra case
  clay.md
  julia-joppien-XFUqd0u5U7w-unsplash.jpg
Labels: Редакция, Мнения, История

#55 Article about clay global
  clay-global/clay.md
  clay-global/preview.jpg
Labels: Редакция, Мнения, История

#56 article about clay global update
  clay-global/clay.md
Labels: Редакция, Мнения, История

#58 added 'tech-vs-life' article
  tech-vs-life/preview.jpg
  tech-vs-life/tech-vs-life.md
Labels: Редакция, Мнения, Колонка Фила

#60 Fix typo
  nat-jun-way/nat-jun-way.md
Labels: Мнения, История, Колонка Наташи

#61 pregnancy-it-girl
  pregnancy-it-girl/image1.png
  pregnancy-it-girl/image10.png
  pregnancy-it-girl/image11.jpg
  pregnancy-it-girl/image12.jpg
  pregnancy-it-girl/image2.jpg
  pregnancy-it-girl/image3.jpg
  pregnancy-it-girl/image4.png
  pregnancy-it-girl/image5.jpg
  pregnancy-it-girl/image6.png
  pregnancy-it-girl/image7.jpg
  pregnancy-it-girl/image8.jpg
  pregnancy-it-girl/image9.jpg
  pregnancy-it-girl/mathieu-stern-1zO4O3Z0UJA-unsplash.jpg
  pregnancy-it-girl/pregnancy-it-girl.md
Labels: Редакция, Интервью, Контекст, История

#62 updated article
  pregnancy-it-girl/i1.png
  pregnancy-it-girl/i10.png
  pregnancy-it-girl/i11.jpg
  pregnancy-it-girl/i12.jpg
  pregnancy-it-girl/i2.jpg
  pregnancy-it-girl/i3.jpg
  pregnancy-it-girl/i4.png
  pregnancy-it-girl/i5.jpg
  pregnancy-it-girl/i6.png
  pregnancy-it-girl/i7.jpg
  pregnancy-it-girl/i8.jpg
  pregnancy-it-girl/i9.jpg
  pregnancy-it-girl/pregnancy-it-girl.md
Labels: Редакция, Интервью, Контекст, История

#64 typefix: скандала
  pregnancy-it-girl/pregnancy-it-girl.md
Labels: Редакция, Интервью, Контекст, История

#65 Add files via upload
  pregnancy-it-girl/i101.png
  pregnancy-it-girl/i11.png
  pregnancy-it-girl/i111.jpg
  pregnancy-it-girl/i121.jpg
  pregnancy-it-girl/i21.jpg
  pregnancy-it-girl/i31.jpg
  pregnancy-it-girl/i41.png
  pregnancy-it-girl/i51.jpg
  pregnancy-it-girl/i61.png
  pregnancy-it-girl/i71.jpg
  pregnancy-it-girl/i81.jpg
  pregnancy-it-girl/i91.jpg
  pregnancy-it-girl/mathieu-stern-1zO4O3Z0UJA-unsplash1.jpg
Labels: Редакция, Интервью, Контекст, История

#66 Hotfix pregnancy it girl
  pregnancy-it-girl/i1011.png
  pregnancy-it-girl/i111.png
  pregnancy-it-girl/i1111.jpg
  pregnancy-it-girl/i1211.jpg
  pregnancy-it-girl/i211.jpg
  pregnancy-it-girl/i311.jpg
  pregnancy-it-girl/i411.png
  pregnancy-it-girl/i511.jpg
  pregnancy-it-girl/i611.png
  pregnancy-it-girl/i711.jpg
  pregnancy-it-girl/i811.jpg
  pregnancy-it-girl/i911.jpg
  pregnancy-it-girl/mathieu-stern-1zO4O3Z0UJA-unsplash11.jpg
  pregnancy-it-girl/pregnancy-it-girl.md
Labels: Редакция, Интервью, Контекст, История

#67 hotfix pregnancy it girl 2
  pregnancy-it-girl/i10112.png
  pregnancy-it-girl/i11112.jpg
  pregnancy-it-girl/i1112.png
  pregnancy-it-girl/i12112.jpg
  pregnancy-it-girl/i2112.jpg
  pregnancy-it-girl/i3112.jpg
  pregnancy-it-girl/i4112.png
  pregnancy-it-girl/i5112.jpg
  pregnancy-it-girl/i6112.png
  pregnancy-it-girl/i7112.jpg
  pregnancy-it-girl/i8112.jpg
  pregnancy-it-girl/i9112.jpg
  pregnancy-it-girl/mathieu-stern-1zO4O3Z0UJA-unsplash112.jpg
  pregnancy-it-girl/pregnancy-it-girl.md
Labels: Редакция, Интервью, Контекст, История

#68 pregn it gitl hotfix 3
  pregnancy-it-girl/i101123.png
  pregnancy-it-girl/i111123.jpg
  pregnancy-it-girl/i11123.png
  pregnancy-it-girl/i121123.jpg
  pregnancy-it-girl/i21123.jpg
  pregnancy-it-girl/i31123.jpg
  pregnancy-it-girl/i41123.png
  pregnancy-it-girl/i51123.jpg
  pregnancy-it-girl/i61123.png
  pregnancy-it-girl/i71123.jpg
  pregnancy-it-girl/i81123.jpg
  pregnancy-it-girl/i91123.jpg
  pregnancy-it-girl/mathieu-stern-1zO4O3Z0UJA-unsplash1123.jpg
  pregnancy-it-girl/pregnancy-it-girl.md
Labels: Редакция, Интервью, Контекст, История

#70 how to teach developers
  how to teach developers/how-to-teach-developers.md
  how to teach developers/preview.jpg
Labels: Редакция, Интервью, Контекст

#71 2pizza story
  2pizza-story/2pizza-story.md
  2pizza-story/connected-to-freedom.jpg
  2pizza-story/preview.jpg
Labels: Редакция, Интервью, История

#76 Pregnancy it girl update
  pregnancy-it-girl/i_0_upd.jpg
  pregnancy-it-girl/i_10_upd.jpg
  pregnancy-it-girl/i_11_upd.png
  pregnancy-it-girl/i_1_upd.png
  pregnancy-it-girl/i_2_upd.png
  pregnancy-it-girl/i_3_upd.jpg
  pregnancy-it-girl/i_4_upd.jpg
  pregnancy-it-girl/i_5_upd.jpg
  pregnancy-it-girl/i_6_upd.png
  pregnancy-it-girl/i_7_upd.jpg
  pregnancy-it-girl/i_8_upd.jpg
  pregnancy-it-girl/i_9_upd.jpg
  pregnancy-it-girl/pregnancy-it-girl.md
  pregnancy-it-girl/preview_0_upd.jpg
Labels: Редакция, Интервью, Контекст, История

#77 Release1 1
  release_1_1/preview.jpg
  release_1_1/release_1_1.md
Labels: Код, Блог разработчика

#80 Alex cuprum story
  alex-cuprum-story/alex-cuprum-story.md
  alex-cuprum-story/preview.jpg
Labels: Редакция, Интервью, История, Релокейт

#72 added sqlite-orm-new-migrations
  sqlite-orm-new-migrations/preview.jpeg
  sqlite-orm-new-migrations/sqlite-orm-new-migrations.md
Labels: Код

#82 replaced preview
  sqlite-orm-new-migrations/p.jpg
  sqlite-orm-new-migrations/preview.jpeg
  sqlite-orm-new-migrations/sqlite-orm-new-migrations.md
Labels: Код

#84 Gleb Miheev article
  gleb_m/gleb-miheev.md
  gleb_m/preview.jpg
Labels: Редакция, Интервью

#85 added article
  sqlite-orm-new-migrations2/preview.jpeg
  sqlite-orm-new-migrations2/sqlite-orm-new-migrations2.md
Labels: Код

#86 fixed preview
  sqlite-orm-new-migrations2/p.jpg
  sqlite-orm-new-migrations2/preview.jpeg
  sqlite-orm-new-migrations2/sqlite-orm-new-migrations2.md
Labels: Код

#87 fix Gleb Miheev article
  gleb_m/gleb-miheev.md
Labels: Редакция, Интервью

#91 bdsm girl article
  BDSM-girl 223/BDSMgirl.md
  BDSM-girl 223/image1.jpg
  BDSM-girl 223/image10.png
  BDSM-girl 223/image11.jpg
  BDSM-girl 223/image12.jpg
  BDSM-girl 223/image13.jpg
  BDSM-girl 223/image14.jpg
  BDSM-girl 223/image15.jpg
  BDSM-girl 223/image16.jpg
  BDSM-girl 223/image17.jpg
  BDSM-girl 223/image18.jpg
  BDSM-girl 223/image19.jpg
  BDSM-girl 223/image2.jpg
  BDSM-girl 223/image20.jpg
  BDSM-girl 223/image21.png
  BDSM-girl 223/image22.jpg
  BDSM-girl 223/image23.jpg
  BDSM-girl 223/image24.jpg
  BDSM-girl 223/image25.jpg
  BDSM-girl 223/image3.jpg
  BDSM-girl 223/image4.png
  BDSM-girl 223/image5.jpg
  BDSM-girl 223/image6.jpg
  BDSM-girl 223/image7.jpg
  BDSM-girl 223/image8.png
  BDSM-girl 223/image9.jpg
  BDSM-girl 223/preview.jpg
Labels: Редакция, Интервью, История

#92 Stay together upd
  stay-together/stay-together.md
Labels: Мнения, Колонка Фила

#93 Conferences
  Conferences/conferences.md
  Conferences/preview.jpg
Labels: Мнения, Контекст, История

#94 conf upd
  Conferences/conferences.md
Labels: Редакция, Мнения, Контекст

#95 yandex news
  yandx-news-1/delivery.jpg
  yandx-news-1/preview.jpg
  yandx-news-1/yandex-news.md
Labels: Контекст

#96 yandex news upd
  yandx-news-1/delivery1.jpg
  yandx-news-1/yandex-news.md
Labels: Контекст

#97 yandex-news-upd
  yandx-news-1/delivery2.jpg
  yandx-news-1/yandex-news.md
Labels: Контекст

#99 podlodka article
  podlodka/podlodka.md
  podlodka/preview.jpg
Labels: Интервью, История

#101 Availbale product
  available-product/1.png
  available-product/10.png
  available-product/12.png
  available-product/13.png
  available-product/2.jpg
  available-product/3.png
  available-product/5.png
  available-product/6.png
  available-product/7.png
  available-product/8.png
  available-product/9.png
  available-product/preview.jpg
  available-product/product.md
Labels: Мнения, Интервью

#102 available upd
  available-product/23.jpg
  available-product/product.md
Labels: Мнения, Интервью

#103 upd
  available-product/10upd.png
  available-product/12upd.png
  available-product/13upd.png
  available-product/1upd.png
  available-product/23upd.jpg
  available-product/3upd.png
  available-product/5upd.png
  available-product/6upd.png
  available-product/7upd.png
  available-product/8upd.png
  available-product/9upd.png
  available-product/product.md
Labels: Мнения, Интервью

#104 Just look at this shit
  just-look-at-this-shit/061A80AC-4BF5-4FD9-ABF4-6CEBB0A22689.png
  just-look-at-this-shit/2F95ABD3-57E5-438A-A431-8F0B5EA17916.png
  just-look-at-this-shit/54E6084B-91F1-4E39-B2B1-FDBB8576F996.png
  just-look-at-this-shit/660B8C59-21CC-4E07-9643-A3F393419C64.png
  just-look-at-this-shit/7E086DBE-638E-4DF4-9F37-C9F95D907890.png
  just-look-at-this-shit/8288490F-0DA5-4076-BDAB-AD30CBAC69B3.png
  just-look-at-this-shit/8680BCBF-C6D8-4E1D-9488-43D334B4B937.png
  just-look-at-this-shit/994EA398-7C5C-478C-BA1A-FEB73D084D55.png
  just-look-at-this-shit/A2BCFF22-2955-40E8-BBC5-C3CADBB25742.png
  just-look-at-this-shit/B3EDA584-AF20-44F9-8DB9-2547E1411153.png
  just-look-at-this-shit/F7935DB1-11D4-42DA-8488-4832BC69F6EA.png
  just-look-at-this-shit/just-look-at-this-shit.md
  just-look-at-this-shit/preview.jpg
Labels: История, Скандальные увольнения

#105 Add files via upload
  just-look-at-this-shit/061A80AC-4BF5-4FD9-ABF4-6CEBB0A22689upd.png
  just-look-at-this-shit/2F95ABD3-57E5-438A-A431-8F0B5EA17916upd.png
  just-look-at-this-shit/54E6084B-91F1-4E39-B2B1-FDBB8576F996upd.png
  just-look-at-this-shit/660B8C59-21CC-4E07-9643-A3F393419C64upd.png
  just-look-at-this-shit/7E086DBE-638E-4DF4-9F37-C9F95D907890upd.png
  just-look-at-this-shit/8288490F-0DA5-4076-BDAB-AD30CBAC69B3upd.png
  just-look-at-this-shit/8680BCBF-C6D8-4E1D-9488-43D334B4B937upd.png
  just-look-at-this-shit/994EA398-7C5C-478C-BA1A-FEB73D084D55upd.png
  just-look-at-this-shit/A2BCFF22-2955-40E8-BBC5-C3CADBB25742upd.png
  just-look-at-this-shit/B3EDA584-AF20-44F9-8DB9-2547E1411153upd.png
  just-look-at-this-shit/F7935DB1-11D4-42DA-8488-4832BC69F6EAupd.png
  just-look-at-this-shit/just-look-at-this-shit.md
Labels: История, Заметки безработного

#106 it startups
  it-startup/1.jpg
  it-startup/2.jpg
  it-startup/3.png
  it-startup/4.jpg
  it-startup/5.jpg
  it-startup/preview.jpg
  it-startup/startups.md
Labels: Мнения, Интервью, Контекст

#108 upd
  it-startup/1-1.png
  it-startup/2-2.png
  it-startup/3-3.png
  it-startup/4-4.png
  it-startup/5-5.png
  it-startup/startups.md
Labels: Мнения, Интервью, Контекст

#109 added article
  no-more-platform/np-more-platform.md
  no-more-platform/preview.jpg
Labels: Редакция, Мнения, Колонка Фила, Код

#110 upd
  no-more-platform/np-more-platform.md
Labels: Редакция, Мнения, Колонка Фила, Код

#111 upd
  no-more-platform/np-more-platform.md
Labels: Редакция, Мнения, Колонка Фила, Код

#112 upd
  no-more-platform/np-more-platform.md
Labels: Редакция, Мнения, Колонка Фила, Код
