Repository razrabs-media/editorial, pull requests merged in 2022-10, with the labels that each got.

#152 added article
  china/china.md
  china/i-0.png
  china/i-1.jpg
  china/i-2.jpg
  china/i-3.jpg
  china/i-4.jpg
  china/i-5.png
  china/i-6.jpg
  china/i-7.jpg
  china/preview.jpg
Labels: Редакция, Релокейт

#153 China
  china/china.md
  china/i_0.png
  china/i_1.jpg
  china/i_2.jpg
  china/i_3.jpg
  china/i_4.jpg
  china/i_5.png
  china/i_6.jpg
  china/i_7.jpg
Labels: Редакция, Релокейт

#154 added article
  bastion/bastion.md
  bastion/i-0.png
  bastion/i-1.png
  bastion/i-10.png
  bastion/i-11.png
  bastion/i-12.png
  bastion/i-13.png
  bastion/i-14.png
  bastion/i-15.png
  bastion/i-2.png
  bastion/i-3.png
  bastion/i-4.jpg
  bastion/i-5.png
  bastion/i-6.png
  bastion/i-7.png
  bastion/i-8.png
  bastion/i-9.png
  bastion/preview.jpg
Labels: Редакция, Контекст

#157 added article
  indonesia/Indonesia.md
  indonesia/image1.png
  indonesia/image10.png
  indonesia/image11.png
  indonesia/image12.png
  indonesia/image13.png
  indonesia/image14.png
  indonesia/image2.png
  indonesia/image3.png
  indonesia/image4.png
  indonesia/image5.png
  indonesia/image6.png
  indonesia/image7.png
  indonesia/image8.png
  indonesia/image9.png
  indonesia/preview.jpg
Labels: Редакция, Релокейт

#160 upd
  haskell/haskell.md
Labels: Редакция, Код

#161 Mobilization2
  mob2/mob2.md
  mob2/preview.jpg
Labels: Редакция, Мнения, Контекст

#162 upd
  mob2/mob2.md
Labels: Редакция, Мнения, Контекст

#163 added comment
  mob2/mob2.md
Labels: Редакция, Мнения, Контекст
