Repository razrabs-media/editorial, pull requests merged in 2022-09, with the labels that each got.

#113 sitnik article
  sitnik/preview.jpg
  sitnik/sitnik.md
Labels: Интервью

#116 added article
  kirill-nikiforov/kirill-nikiforov.md
  kirill-nikiforov/preview.jpg
Labels: Редакция, Интервью, История

#120 Update sitnik.md
  sitnik/sitnik.md
Labels: Редакция, Мнения, Интервью

#121 Ru it tragedy
  ru-it-tragedy/preview.jpg
  ru-it-tragedy/ru-it-tragedy.md
Labels: Редакция, Мнения, Колонка Фила

#123 added article
  sber-story/preview.jpg
  sber-story/sber-story.md
Labels: Редакция, Интервью

#124 added article
  mail-ru-story/mail-ru-story.md
  mail-ru-story/preview.jpg
Labels: Редакция, Интервью

#125 upd mail
  mail-ru-story/mail-ru-story.md
Labels: Редакция, Интервью

#126 mail upd
  mail-ru-story/mail-ru-story.md
Labels: Редакция, Интервью

#127 mail upd
  mail-ru-story/mail-ru-story.md
Labels: Редакция, Интервью

#129 upd mail
  mail-ru-story/mail-ru-story.md
Labels: Редакция, Интервью

#130 added article
  itsover/Preview.png
  itsover/itsover.md
Labels: Редакция

#131 Update itsover.md
  itsover/itsover.md
Labels: Редакция

#132 fix
  itsover/itsover.md
  itsover/p.png
Labels: Редакция

#133 added article
  mobilization/i0.png
  mobilization/i1.png
  mobilization/i10.png
  mobilization/i2.png
  mobilization/i3.png
  mobilization/i4.png
  mobilization/i5.png
  mobilization/i6.png
  mobilization/i7.png
  mobilization/i8.png
  mobilization/i9.png
  mobilization/mobilization.md
  mobilization/preview.png
Labels: Редакция, Контекст, Релокейт

#134 fix
  mobilization/img0.png
  mobilization/img1.png
  mobilization/img10.png
  mobilization/img2.png
  mobilization/img3.png
  mobilization/img4.png
  mobilization/img5.png
  mobilization/img6.png
  mobilization/img7.png
  mobilization/img8.png
  mobilization/img9.png
  mobilization/mobilization.md
Labels: Редакция, Контекст, Релокейт

#135 fix
  mobilization/img-0.png
  mobilization/img-1.png
  mobilization/img-10.png
  mobilization/img-2.png
  mobilization/img-3.png
  mobilization/img-4.png
  mobilization/img-5.png
  mobilization/img-6.png
  mobilization/img-7.png
  mobilization/img-8.png
  mobilization/img-9.png
  mobilization/mobilization.md
  mobilization/p.png
  mobilization/preview.png
Labels: Редакция, Контекст, Релокейт

#136 fix
  mobilization/img-1.png
  mobilization/img-2.png
  mobilization/img-3.png
  mobilization/img-4.png
  mobilization/img-5.png
  mobilization/img-6.png
  mobilization/img-7.png
  mobilization/img-8.png
  mobilization/img-9.png
  mobilization/img_0.png
  mobilization/img_1.png
  mobilization/img_10.png
  mobilization/img_2.png
  mobilization/img_3.png
  mobilization/img_4.png
  mobilization/img_5.png
  mobilization/img_6.png
  mobilization/img_7.png
  mobilization/img_8.png
  mobilization/img_9.png
  mobilization/mobilization.md
Labels: Редакция, Контекст, Релокейт

#137 fix
  mobilization/img--0.png
  mobilization/img--1.png
  mobilization/img--10.png
  mobilization/img--2.png
  mobilization/img--3.png
  mobilization/img--4.png
  mobilization/img--5.png
  mobilization/img--6.png
  mobilization/img--7.png
  mobilization/img--8.png
  mobilization/img--9.png
  mobilization/img_1.png
  mobilization/mobilization.md
Labels: Редакция, Контекст, Релокейт

#138 fix
  mobilization/im-0.png
  mobilization/im-1.png
  mobilization/im-10.png
  mobilization/im-2.png
  mobilization/im-3.png
  mobilization/im-4.png
  mobilization/im-5.png
  mobilization/im-6.png
  mobilization/im-7.png
  mobilization/im-8.png
  mobilization/im-9.png
  mobilization/mobilization.md
Labels: Редакция, Контекст, Релокейт

#139 added article
  runaway/preview.png
  runaway/runaway.md
Labels: Редакция, Контекст, Релокейт

#140 fix
  runaway/p.png
  runaway/preview.png
  runaway/runaway.md
Labels: Редакция, Контекст, Релокейт

#141 Update runaway.md
  runaway/runaway.md
Labels: Редакция, Контекст, Релокейт

#142 runaway: fix jetbrains destinations
  runaway/runaway.md
Labels: Редакция, Контекст, Релокейт

#144 Update runaway.md
  runaway/runaway.md
Labels: Редакция, Контекст, Релокейт

#146 Singapore
  singapore/i-0.png
  singapore/i-1.jpg
  singapore/i-10.jpg
  singapore/i-11.jpg
  singapore/i-12.jpg
  singapore/i-13.jpg
  singapore/i-14.jpg
  singapore/i-15.jpg
  singapore/i-16.jpg
  singapore/i-17.jpg
  singapore/i-2.jpg
  singapore/i-3.jpg
  singapore/i-4.jpg
  singapore/i-5.jpg
  singapore/i-6.jpg
  singapore/i-7.jpg
  singapore/i-8.jpg
  singapore/i-9.jpg
  singapore/preview.jpg
  singapore/singapore.md
Labels: Редакция, Интервью, Контекст, Релокейт

#149 Добавил компанию Findmykids
  runaway/runaway.md
Labels: Редакция, Контекст, Релокейт
