Repository razrabs-media/editorial, pull requests merged in 2023-12, with the labels that each got.

#206 Стоит ли искать работу перед...
  newyearjob/newyearjob.md
  newyearjob/preview.jpg
Labels: Мнения

#207 Стоит ли устраиваться на работу перед...
  newyearjob/newyearjob.md
Labels: Мнения

#210 Update incompetence-vs-dismissal.md
  incompetence-vs-dismissal/incompetence-vs-dismissal.md
Labels: Мнения

#211 Video-ios-dev
  video-iOS-dev/preview.jpg
  video-iOS-dev/video-iOS-dev.md
Labels: Подкаст Разрабы

#214 Update incompetence-vs-dismissal.md
  incompetence-vs-dismissal/incompetence-vs-dismissal.md
Labels: Мнения

#215 Код или бизнес...
  video-code-or-business/preview.jpg
  video-code-or-business/video-code-or-business.md
Labels: Подкаст Разрабы

#216 Крутые хобби для разрабов...
  video-hobbies/preview.jpg
  video-hobbies/video-hobbies.md
Labels: Подкаст Разрабы

#217 Почему так трудно войти в IT...
  video-enter-it/preview.jpg
  video-enter-it/video-enter-it.md
Labels: Подкаст Разрабы

#218 Тимлид — нелепая бутафорская должность...
  teamlead-ridiculous-position/preview.jpg
  teamlead-ridiculous-position/teamlead-ridiculous-position.md
Labels: Мнения, Колонка Фила

#220 Тимлид — нелепая бутафорская должность...
  teamlead-ridiculous-position/teamlead-ridiculous-position.md
Labels: Мнения, Колонка Фила

#221 Профессиональный хоккеист выучил Ruby...
  video-hockey-to-it/preview.jpg
  video-hockey-to-it/video-hockey-to-it.md
Labels: Подкаст Разрабы

#222 Путь от джуна-разраба до деврела...
  video-june-to-devrel/preview.jpg
  video-june-to-devrel/video-june-to-devrel.md
Labels: Подкаст Разрабы

#223 Update video-june-to-devrel.md
  video-june-to-devrel/video-june-to-devrel.md
Labels: Подкаст Разрабы

#224 Всё про путешествия и цифровое кочевничество...
  video-digital-nomads/preview.jpg
  video-digital-nomads/video-digital-nomads.md
Labels: Подкаст Разрабы
