Repository razrabs-media/editorial, pull requests merged in 2023-10, with the labels that each got.

#191 Serbian Quiz List story
  SerbQuizList/cinema.jpg
  SerbQuizList/end.jpg
  SerbQuizList/murm.JPG
  SerbQuizList/preview2.jpg
  SerbQuizList/story.md
Labels: История

#193 Как я разработал симулятор продаж и деловых продаж SkyTrainer
  sky-trainer-about/1.jpg
  sky-trainer-about/2.jpg
  sky-trainer-about/preview.jpg
  sky-trainer-about/sky-trainer-about.md
Labels: История

#196 Дипломированный философ, всю жизнь делающий трюки на велосипеде
  startup-swap/preview.png
  startup-swap/startup-swap.md
Labels: Контекст, История

#198 Безопасный путь релокации...
  emigration-to-egypt/emigration-to-egypt.md
  emigration-to-egypt/image1.jpg
  emigration-to-egypt/image2.jpg
  emigration-to-egypt/image3.jpg
  emigration-to-egypt/image4.png
  emigration-to-egypt/image5.jpg
  emigration-to-egypt/image6.jpg
Labels: История, Релокейт

#199 Безопасный путь релокации...
  emigration-to-egypt/emigration-to-egypt.md
Labels: История, Релокейт
