Repository razrabs-media/editorial, pull requests merged in 2023-01, with the labels that each got.

#183 Enter to it
  enter-to-it/enter-to-it.md
  enter-to-it/image1.jpg
  enter-to-it/image10.png
  enter-to-it/image11.jpg
  enter-to-it/image12.jpg
  enter-to-it/image13.png
  enter-to-it/image14.jpg
  enter-to-it/image2.jpg
  enter-to-it/image3.png
  enter-to-it/image4.jpg
  enter-to-it/image5.jpg
  enter-to-it/image6.png
  enter-to-it/image7.jpg
  enter-to-it/image8.png
  enter-to-it/image9.jpg
  enter-to-it/preview.jpg
Labels: Редакция, Интервью, История

#184 upd
  enter-to-it/enter-to-it.md
  enter-to-it/image6.png
  enter-to-it/img.jpg
Labels: Редакция, Интервью, История

#185 added article
  uzbekistan/image1.jpg
  uzbekistan/image10.png
  uzbekistan/image11.png
  uzbekistan/image12.png
  uzbekistan/image13.png
  uzbekistan/image14.png
  uzbekistan/image15.png
  uzbekistan/image16.png
  uzbekistan/image17.png
  uzbekistan/image2.png
  uzbekistan/image3.png
  uzbekistan/image4.png
  uzbekistan/image5.png
  uzbekistan/image6.png
  uzbekistan/image7.png
  uzbekistan/image8.png
  uzbekistan/image9.png
  uzbekistan/preview.jpg
  uzbekistan/uzbekistan.md
Labels: Редакция, Интервью, Релокейт

#186 added article
  israel/Israel.md
  israel/image1.jpg
  israel/image10.jpg
  israel/image11.jpg
  israel/image2.jpg
  israel/image3.jpg
  israel/image4.jpg
  israel/image5.jpg
  israel/image6.jpg
  israel/image7.jpg
  israel/image8.jpg
  israel/image9.jpg
  israel/preview.jpg
Labels: Редакция, Интервью, История, Релокейт

#187 added article
  sefer/i-0.jpg
  sefer/i-1.jpg
  sefer/i-2.jpg
  sefer/i-3.jpg
  sefer/i-4.png
  sefer/preview.jpg
  sefer/serfer.md
Labels: Интервью, История

#188 upd
  sefer/serfer.md
Labels: Редакция, Интервью, История
