Repository razrabs-media/editorial, pull requests merged in 2024-02, with the labels that each got.

#237 Кто теперь главный по Котлину...
  video-kotlin/preview.jpg
  video-kotlin/video-kotlin.md
Labels: Подкаст Разрабы

#240 Тихая революция...
  silent-revolution-1/eight.png
  silent-revolution-1/five.png
  silent-revolution-1/four.jpg
  silent-revolution-1/nine.jpeg
  silent-revolution-1/one.jpeg
  silent-revolution-1/preview.jpg
  silent-revolution-1/seven.jpeg
  silent-revolution-1/silent-revolution-1.md
  silent-revolution-1/six.png
  silent-revolution-1/ten.png
  silent-revolution-1/three.jpg
  silent-revolution-1/two.jpg
Labels: Мнения

#243 Update viedo-whos-in-charge.md
  video-whos-in-charge/viedo-whos-in-charge.md
Labels: Подкаст Разрабы

#244 How to become a great software developer...
  video-best-advice/preview.jpg
  video-best-advice/video-best-advice.md
Labels: Подкаст Разрабы

#247 Как выдержать критику...
  video-criticism/preview.jpg
  video-criticism/video-criticism.md
Labels: Подкаст Разрабы

#248 Update ghost-of-communism.md
  ghost-of-communism/ghost-of-communism.md
Labels: Редакция, Мнения, Написано без помощи ИИ

#249 Сообщество спасёт...
  video-community-saves/preview.jpg
  video-community-saves/video-community-saves.md
Labels: Подкаст Разрабы

#250 Как стать крутым IT-рекрутером...
  video-how-to-recruit/preview.jpg
  video-how-to-recruit/video-how-to-recruit.md
Labels: Подкаст Разрабы

#251 Склеил 100500 девушек с ChatGPT...
  video-neuropickup/preview.jpg
  video-neuropickup/video-neuropickup.md
Labels: Подкаст Разрабы
