Repository razrabs-media/editorial, pull requests merged in 2025-03, with the labels that each got.

#320 Add files via upload
  SDET/image2.jpg
  SDET/preview.jpg
  SDET/sdet
Labels: Редакция, История

#321 Rename sdet to sdet.md
  SDET/sdet.md
Labels: Редакция, Мнения

#322 Add files via upload
  downsizing_not_ judgement/downsizing_not_ judgement
  downsizing_not_ judgement/image1.jpg
  downsizing_not_ judgement/image2.jpg
  downsizing_not_ judgement/image3.jpg
  downsizing_not_ judgement/preview.jpg
Labels: Редакция, История

#324 Update downsizing_not_ judgement.md
  downsizing_not_ judgement/downsizing_not_ judgement.md
Labels: Редакция, Интервью

#325 Add files via upload
  hackers_in_the_head/hackers_in_the head.md
  hackers_in_the_head/preview.jpg
Labels: Редакция, Мнения

#326 Update hackers_in_the head.md
  hackers_in_the_head/hackers_in_the head.md
Labels: Редакция, Мнения

#329 Add files via upload
  Security_through/Security_through_ the_eyes.md
  Security_through/image1.png
  Security_through/image2.png
  Security_through/image3.jpg
  Security_through/image4.jpg
  Security_through/image6.png
  Security_through/image7.png
  Security_through/prew.jpg
Labels: Редакция, Мнения

#330 Update Security_through_ the_eyes.md
  Security_through/Security_through_ the_eyes.md
Labels: Редакция, Мнения

#332 Update Security_through_ the_eyes.md
  Security_through/Security_through_ the_eyes.md
Labels: Редакция, Мнения

#334 Add files via upload
  Security_through/Security_through_ the_eyes.md
  Security_through/image9.png
Labels: Редакция, Мнения

#335 added digital-heart article
  digital-heart/digital-heart.md
  digital-heart/preview.jpg
Labels: Редакция, Мнения, История

#336 Add files via upload
  votkinsk/1.jpg
  votkinsk/2.jpg
  votkinsk/3.png
  votkinsk/4.png
  votkinsk/5.png
  votkinsk/6.png
  votkinsk/7.png
  votkinsk/img1.jpg
  votkinsk/img2.jpg
  votkinsk/img3.jpg
  votkinsk/prew.jpg
  votkinsk/votkinsk.md
Labels: Редакция, История

#337 Add files via upload
  it_coffe/1.png
  it_coffe/2.jpg
  it_coffe/3.jpg
  it_coffe/4.jpg
  it_coffe/5.jpg
  it_coffe/6-1.png
  it_coffe/6.png
  it_coffe/7.png
  it_coffe/8.png
  it_coffe/ITcoffe.md
  it_coffe/prew.jpg
Labels: Редакция, История

#338 Add files via upload
  Playing_high_level/1.png
  Playing_high_level/2.png
  Playing_high_level/3.png
  Playing_high_level/4.jpg
  Playing_high_level/5.png
  Playing_high_level/6.png
  Playing_high_level/7.png
  Playing_high_level/8.png
  Playing_high_level/Playing_high_level.md
  Playing_high_level/prew.jpg
Labels: Редакция, Мнения, История

#340 Update Pilot_Boeing.md
  Pilot_a_Boeing/Pilot_Boeing.md
Labels: Редакция, Мнения, Код
